output "service_principal_application_id" {
  description = "The object id of service principal. Can be used to assign roles to user."
  value       = azuread_application.create_azuread_application.client_id
}

output "service_principal_name" {
  description = "The display name of the application associated with this service principal."
  value       = azuread_service_principal.create_service_principal.display_name
}

output "service_principal_tenant_id" {
  description = "The tenant ID where the associated application is registered."
  value = azuread_service_principal.create_service_principal.application_tenant_id
}

output "service_principal_object_id" {
  description = "The object ID of the service principal."
  value       = azuread_service_principal.create_service_principal.object_id
}

output "service_principal_client_id" {
  description = "A UUID used to uniquely identify this password credential."
  value = azuread_service_principal_password.create_service_principal_password.key_id
}

output "service_principal_client_secret" {
  description = " The password for this service principal, which is generated by Azure Active Directory."
  value       = azuread_service_principal_password.create_service_principal_password.value
}
