---

ubuntu_list_package:
  - bash-completion
  - apt-transport-https 
  - ca-certificates 
  - software-properties-common
  - sshpass
  - curl
  - wget
  - git
  - jq
  - iputils-ping
  - net-tools
  - unzip
  - xorriso
