---
namespace: kubernetes_sigs
description: Deploy a production ready Kubernetes cluster
name: kubespray
version: 2.26.0
readme: README.md
authors:
  - The Kubespray maintainers (https://kubernetes.slack.com/channels/kubespray)
tags:
  - infrastructure
repository: https://github.com/kubernetes-sigs/kubespray
issues: https://github.com/kubernetes-sigs/kubespray/issues
documentation: https://kubespray.io
license_file: LICENSE
dependencies:
  ansible.utils: '>=2.5.0'
  community.general: '>=3.0.0'
manifest:
  directives:
    - recursive-exclude tests **
