name: Build Docker Image with requirements
run-name: >
  Build Dockerfile for ${{ inputs.build-type }} at ${{ inputs.build_site }}

on:
  workflow_call:
  workflow_dispatch:
    inputs:

      build_site:
        type: choice
        description: "Environments for deployment. Used for Github Action.(e.g. LAB, PRD...)"
        required: true
        default: 'hcm-lab'
        options:
          - "hcm-lab"
          - "hcm-prd"

      build-type:
        description: 'Specify the type to build the Dockerfile'
        required: true
        default: 'application'
        type: choice
        options:
          - 'application'
          - 'infrastructure'

jobs:
  build_docker_images:
    runs-on: [self-hosted, "${{ inputs.build_site }}"]
    environment: "${{ inputs.build_site }}"

    container:
      image: docker:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ inputs.build_site }}-${{ inputs.build-type }}-latest
            type=raw,value=${{ inputs.build_site }}-${{ inputs.build-type }}-{{ date 'YYMMDD' }}
            type=sha,prefix=${{ inputs.build_site }}-${{ inputs.build-type }}
          labels: |
            org.opencontainers.image.description="Requirements version: ${{ github.sha }}"

      - name: Docker build arguments
        run: |
          if [ "${{ inputs.build-type }}" == "application" ]; then
            echo "CONTEXT=./application" >> $GITHUB_ENV
            echo "BUILD_CONTEXTS=requirements=application/requirements" >> $GITHUB_ENV
            echo "BUILD_ARGS=TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> $GITHUB_ENV
          else
            echo "CONTEXT=./infrastructure" >> $GITHUB_ENV
            echo "BUILD_CONTEXTS=requirements=infrastructure/requirements" >> $GITHUB_ENV
            echo "BUILD_ARGS=" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          no-cache: true
          context: ${{ env.CONTEXT }}
          build-contexts: ${{ env.BUILD_CONTEXTS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ env.BUILD_ARGS }}
